dist: trusty
sudo: required

language: python
python:
  - "2.7"

services:
  - rabbitmq
  - mysql

env:
  - DBNAME=ottertune
  - DBUSER=root
  - WEBSITE_ROOT=server/website
  - COLON=:

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-pip python-dev python-mysqldb
  - sudo pip install -q -r ${WEBSITE_ROOT}/requirements.txt
  - mysql -e "CREATE DATABASE IF NOT EXISTS ${DBNAME};"
  - mysql -e "CREATE DATABASE IF NOT EXISTS test_${DBNAME};"

before_script:
  - cp ${WEBSITE_ROOT}/website/settings/credentials_TEMPLATE.py
       ${WEBSITE_ROOT}/website/settings/credentials.py;
    sed -i
        -e "s/^DEBUG.*/DEBUG = True/"
        -e "s/'USER'${COLON} 'ADD ME\!\!'/'USER'${COLON} '${DBUSER}'/"
        -e "s/'PASSWORD'${COLON} 'ADD ME\!\!'/'PASSWORD'${COLON} ''/"
        ${WEBSITE_ROOT}/website/settings/credentials.py;

script:
  - cd ${WEBSITE_ROOT} && python manage.py test